
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfwfenuykfsxdpudktts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmd2ZlbnV5a2ZzeGRwdWRrdHRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MDAzMDgsImV4cCI6MjA1NzE3NjMwOH0.i75MgDd_rFnJ-UqLlO0CHsYwZVT5E-XmJL1Zzt-Gzok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export type Tables = Database['public']['Tables']
export type Profile = Tables['profiles']['Row']

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
