
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnyafdikauktfnoxfmfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndueWFmZGlrYXVrdGZub3hmbWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzMjcxNjYsImV4cCI6MjA1MzkwMzE2Nn0.9S50epjhOfRk_GM9tRs3T06agRAyVJO8ZVvi_41TRlA";

// Define the Profile type
export interface Profile {
  id: string;
  full_name: string | null;
  avatar_url: string | null;
  role: string;
  created_at: string;
  updated_at: string;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
